### ISSUE TITLE
Does integrate Redux-Form is needed?

### ISSUE THREAD

**Issue by XeCtvi** [just4fun/stuhome#37]
Hi @just4fun ,

You are doing a good job and thank you for open source your app that helps me a lot on developing my RN application.

And for the app, do we need to integrate the Redux-Form?

What do you think of that?

Thanks.

**Comment by just4fun** [comment]
@XeCtvi - Thanks for you question about this app, even I'd like to treat issue list of GitHub as bug tracker, I'm also happy to have discussion on tech stack with you.

- This app is *side project*. The main reason I created this app is to learn React and Redux. When I heard redux-saga, which can move all async code created by redux-thunk (aka side effects) to another place (saga), I introduced it into app. When I noticed Navigator of React Native has been removed from v0.4x, I introduced react-navigation. That said, I'm always enjoying introduce new tech stack or any cool libraries into this app to learn new things. I can do it, because there is no much risk for side project, it's not a project in a huge company, which should get approved from high level guys to introduce new things.

- The tech stack for this app is *deprecated*. As far as I know, redux-observable is more cool and I like rxjs very much, instead of playing with generator in redux-saga. However, I was busy in routine work so I really have rare time to refactor it. There were many suggestions from students about this app like #34 , so I always consider the feedback from customers as high priority.

- Sorry to answer your question in last place. I haven't used redux-form before, but I think it's a simple approach to help you play with form in redux application. As you know, react team suggested to use [controlled components](https://reactjs.org/docs/forms.html#controlled-components) to implement forms. In this way, you should write event handler and do validation for each of them. In Angular, we have data binding, so we can achieve them easily, but in React we should add more redux stuff. I think redux-form do something similar with Angular data-binding, to help you reducing boilerplate code. As for this app, the forms are pretty simple (login form, topic publish form, comment reply form), so I used controlled components directly.

At last, I'd like to share one more thought. You have no need to use every new created library into your app until you notice it's necessary.

Thanks.

**Comment by XeCtvi** [comment]
Hi @just4fun ,

Many Thanksssss for your kind suggestions. I am getting familiar with react native development now that your app helps me a lot. And I fully understand what you are concern.

All in all, I have no question for now. Best wishes to you  ;)
